### PR TITLE
fix for VisualF# issue #3729

### PR DESCRIPTION
**Pull request by ingted**
Hi, 

According to this, 
https://github.com/Microsoft/visualfsharp/pull/3729

I made these changes to let this project able to be compiled with VS2017 update 15.4

Please take a look!

Regards
Anibal

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
Thanks, but Tuple`8 types are not exactly the same as a tuple of 8 elements. In order to get this to work, the F# compiler issue must be fixed.

**Comment by dsyme** [comment]
> In order to get this to work, the F# compiler issue must be fixed.

There should be a reflection-based fix for this?

**Comment by eiriktsarpalis** [comment]
@dsyme I think I would rather wait until the issue gets fixed. Can always build using older versions.

**Comment by 0x53A** [comment]
Build _should_ still work with any version of VS because the project uses FSharp.Compiler.Tools.
That doesn't, however, help with intellisense, so you probably get red squiggles in the code:

grafik


So ... as long as you don't update the version of FSharp.Compiler.Tools, you are safe.

**Pull request closed without merging**
