### PR TITLE
Fix struct record/union serialization for code generated picklers

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
cc @varon @dsyme

### CODE REVIEW

**Comment by dsyme** [comment]
Looks good but there's a CI failure?

**Comment by eiriktsarpalis** [comment]
@dsyme seems to be failing in mono

**Comment by dsyme** [comment]
Yes. "  ----> System.ArgumentException : method arguments are incompatible"

I think the Mono 5.0.x has all the right F# bits, so this feels like either a Mono bug or an FsPickler bug.  But I might be wrong - perhaps there is an F# fix missing from Mono 5.0.x

```
1) Test Error : MBrace.FsPickler.Tests.Generic Tests.1. Correctly resolve finite types
   MBrace.FsPickler.PicklerGenerationException : Error generating pickler for type 'MBrace.FsPickler.Tests.TestTypes+StructDU'.
  ----> System.ArgumentException : method arguments are incompatible
  at MBrace.FsPickler.PicklerResolution.resolvePickler (MBrace.FsPickler.IPicklerResolver resolver, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] mkEarlyBinding, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] isPicklerReferenced, System.Type t) [0x00194] in <5945b0535ec56bbba745038353b04559>:0 
```

**Comment by dsyme** [comment]
@eiriktsarpalis What was the cause of the Mono bug?

**Comment by eiriktsarpalis** [comment]
@dsyme apparently the reflection-based pickler for unions didn't work with structs in mono

**Pull request merged**
