### PR TITLE
Type.GetMember() returns nondeterministic orderings of fields/members

### PR DESCRIPTION
**Pull request by haraldsteinlechner**
see: https://github.com/mbraceproject/FsPickler/issues/92

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
Looks like there are failing tests in mono

**Comment by haraldsteinlechner** [comment]
strange, on my local machine it works (arch linux, mono 5.0.0)

**Comment by eiriktsarpalis** [comment]
travis seems to be running 5.2. Maybe it's a new mono bug?

**Comment by haraldsteinlechner** [comment]
thanks. seems you fixed the mono problem? what was the problem?

**Comment by eiriktsarpalis** [comment]
Looks like HashSet serialization was broken in 5.2

**Pull request merged**
